# Generated by Django 4.2.5 on 2024-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
