# Generated by Django 4.2.5 on 2024-01-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_employees_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='mobilenumber',
        ),
    ]
