# Generated by Django 4.2.5 on 2024-01-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_navitem_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavItem',
            new_name='DropdownItem',
        ),
    ]
