# Generated by Django 4.2.5 on 2024-01-11 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_rename_navitem_dropdownitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.navbar'),
        ),
    ]
