# Generated by Django 4.2.5 on 2024-01-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0011_remove_dropdownitem_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DropdownItem',
            new_name='Dropdown',
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('dropdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.dropdown')),
            ],
        ),
    ]
