# Generated by Django 4.2.5 on 2024-01-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_rename_dropdownitem_dropdown_navitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='dropdown',
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
