# Generated by Django 4.2.5 on 2024-01-29 09:20

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0017_remove_navitem_dropdown_delete_dropdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('drop_slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('nav_slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('item_slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title')),
                ('dropdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.dropdown')),
            ],
        ),
        migrations.AddField(
            model_name='dropdown',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.navbar'),
        ),
    ]
