# Generated by Django 4.2.5 on 2024-01-29 13:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0019_alter_dropdown_drop_slug_alter_navbar_nav_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('items_slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title')),
                ('dropdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.dropdown')),
                ('navitems', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.navitem')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
