# Generated by Django 4.2.5 on 2024-01-31 12:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0021_items_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='drop_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='nav_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='item_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
        ),
    ]
