# Generated by Django 4.2.5 on 2024-02-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0022_alter_dropdown_drop_slug_alter_items_items_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dropdown',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name_plural': 'Navbar'},
        ),
        migrations.AlterModelOptions(
            name='navitem',
            options={'verbose_name_plural': 'NavItem'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
