# Generated by Django 4.2.5 on 2024-02-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0024_rename_navitem_subcategory_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='dropdown',
        ),
        migrations.RemoveField(
            model_name='items',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='items',
            name='navitems',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='dropdown',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
