# Generated by Django 4.2.5 on 2024-02-01 12:45

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0025_remove_items_dropdown_remove_items_navbar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('img', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('img', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Navbar',
                'db_table': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('img', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategory',
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('dis_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('org_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('item_img', models.URLField(blank=True, max_length=7000, null=True)),
                ('conditions', models.CharField(max_length=10000)),
                ('offer', models.CharField(max_length=5000)),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('description', models.TextField(default=0, max_length=10000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.category')),
                ('navbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.navbar')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'Items',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.navbar'),
        ),
    ]
