# Generated by Django 4.2.5 on 2024-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0026_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_img',
            field=models.URLField(max_length=7000, null=True),
        ),
    ]
