# Generated by Django 4.2.5 on 2024-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0027_alter_items_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_img',
        ),
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.URLField(max_length=7000, null=True),
        ),
    ]
