# Generated by Django 4.2.5 on 2024-02-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0034_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
