# Generated by Django 4.2.5 on 2024-02-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0036_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], default='In Progress', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.userprofile')),
            ],
        ),
    ]
