# Generated by Django 4.2.5 on 2024-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0038_alter_userprofile_options_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
