# Generated by Django 4.2.5 on 2024-02-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0043_userprofile_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
