# Generated by Django 5.0.1 on 2024-02-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0049_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Brand_name',
            new_name='company_name',
        ),
    ]
