# Generated by Django 4.2.5 on 2024-02-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0052_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
